// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_verses from "./routes/api/v1/verses.ts";
import * as $catechism_index from "./routes/catechism/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_feed from "./routes/partials/feed.tsx";
import * as $proverbs_proverb_ from "./routes/proverbs/[proverb].tsx";
import * as $proverbs_index from "./routes/proverbs/index.tsx";
import * as $psalms_psalm_ from "./routes/psalms/[psalm].tsx";
import * as $psalms_index from "./routes/psalms/index.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $Onboarding from "./islands/Onboarding.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/verses.ts": $api_v1_verses,
    "./routes/catechism/index.tsx": $catechism_index,
    "./routes/index.tsx": $index,
    "./routes/partials/feed.tsx": $partials_feed,
    "./routes/proverbs/[proverb].tsx": $proverbs_proverb_,
    "./routes/proverbs/index.tsx": $proverbs_index,
    "./routes/psalms/[psalm].tsx": $psalms_psalm_,
    "./routes/psalms/index.tsx": $psalms_index,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/Onboarding.tsx": $Onboarding,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
