// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_verses from "./routes/api/v1/verses.ts";
import * as $bible_id_ from "./routes/bible/[id].tsx";
import * as $bible_index from "./routes/bible/index.tsx";
import * as $catechism_index from "./routes/catechism/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $partials_feed from "./routes/partials/feed.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $Onboarding from "./islands/Onboarding.tsx";
import * as $Toolbar from "./islands/Toolbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/verses.ts": $api_v1_verses,
    "./routes/bible/[id].tsx": $bible_id_,
    "./routes/bible/index.tsx": $bible_index,
    "./routes/catechism/index.tsx": $catechism_index,
    "./routes/index.tsx": $index,
    "./routes/partials/feed.tsx": $partials_feed,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/Onboarding.tsx": $Onboarding,
    "./islands/Toolbar.tsx": $Toolbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
